In [2]:
import pandas as pd
from pathlib import Path

In [16]:
data_dir = Path.cwd().parent / "data"

In [18]:
arquivos = [f"despesa_ceaps_{ano}.csv" for ano in range(2019, 2023)]

despesa_ceaps = pd.concat([pd.read_csv(data_dir / arquivo, sep=";", encoding="latin1", skiprows=1)
                            for arquivo in arquivos],
                            ignore_index=True)

despesa_ceaps

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,COD_DOCUMENTO
0,2019,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ENERGISA,006582758,04/01/2019,Despesa com pagamento de energia elétrica do e...,"66,02",2116543
1,2019,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ENERGISA,006582755,04/01/2019,Despesa com pagamento de energia elétrica do e...,"139,98",2116546
2,2019,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,00119,07/01/2019,Despesa com pagamento de aluguel de imóvel par...,6000,2113817
3,2019,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.423.963/0001-11,OI MÓVEL S.A.,86161151,25/12/2018,Despesa com pagamento de telefonia para o escr...,"316,39",2116541
4,2019,2,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ENERGISA,007236036,04/02/2019,Despesa com pagamento de energia elétrica para...,"99,45",2116550
...,...,...,...,...,...,...,...,...,...,...,...
69351,2022,12,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,WIXHAI,06/12/2022,"Companhia Aérea: LATAM, Localizador: WIXHAI. P...","2893,04",2191398
69352,2022,12,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,WITOLM,09/12/2022,"Companhia Aérea: GOL, Localizador: WITOLM. Pas...","1180,19",2192272
69353,2022,12,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,THPKVQ,20/12/2022,"Companhia Aérea: TAM, Localizador: THPKVQ. Pas...","2671,9",2192274
69354,2022,12,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,QNN9HX,21/12/2022,"Companhia Aérea: AZUL, Localizador: QNN9HX. Pa...","1334,31",2192244
69355,2022,12,ZEQUINHA MARINHO,"Passagens aéreas, aquáticas e terrestres nacio...",22.052.777/0001-32,Exceller Tour,WMQWBX,30/12/2022,"Companhia Aérea: TAM, Localizador: WMQWBX. Pas...","2250,72",2193622

In [5]:
despesa_ceaps = despesa_ceaps.drop(['CNPJ_CPF', 'DOCUMENTO', 'COD_DOCUMENTO'], axis=1)

In [6]:
despesa_ceaps.dtypes

ANO                   int64
MES                   int64
SENADOR              object
TIPO_DESPESA         object
FORNECEDOR           object
DATA                 object
DETALHAMENTO         object
VALOR_REEMBOLSADO    object
dtype: object

In [7]:
despesa_ceaps['VALOR_REEMBOLSADO'] = despesa_ceaps['VALOR_REEMBOLSADO'].str.replace('.', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [8]:
despesa_ceaps[['ANO', 'MES']] = despesa_ceaps[['ANO', 'MES']].astype(str)

In [9]:
despesa_ceaps.loc[[10986, 31996, 37872], ['ANO','DATA']]

        ANO        DATA
10986  2019  31/01/0219
31996  2020  05/05/0202
37872  2021  29/10/0202

In [10]:
despesa_ceaps.loc[10986, 'DATA'] = '31/01/2019'
despesa_ceaps.loc[31996, 'DATA'] = '05/05/2020'
despesa_ceaps.loc[37872, 'DATA'] = '29/10/2021'

In [11]:
despesa_ceaps.loc[[10986, 31996, 37872], ['ANO','DATA']]

        ANO        DATA
10986  2019  31/01/2019
31996  2020  05/05/2020
37872  2021  29/10/2021

In [12]:
despesa_ceaps['DATA'] = pd.to_datetime(despesa_ceaps['DATA'], format='%d/%m/%Y', errors = 'coerce').dt.date

In [13]:
despesa_ceaps.dtypes

ANO                   object
MES                   object
SENADOR               object
TIPO_DESPESA          object
FORNECEDOR            object
DATA                  object
DETALHAMENTO          object
VALOR_REEMBOLSADO    float64
dtype: object

In [14]:
despesa_ceaps.isnull().sum()

ANO                      0
MES                      0
SENADOR                  0
TIPO_DESPESA             0
FORNECEDOR               0
DATA                     0
DETALHAMENTO         30773
VALOR_REEMBOLSADO        0
dtype: int64

In [15]:
despesa_ceaps.fillna('Nao preenchido', inplace=True)